### ISSUE TITLE
about the school_data

### ISSUE THREAD

**Issue by ckqsars** [chcorbi/MultiTaskLearning#1]
I want to know the detail of the school_data's feature.
It's means the meaning in different columns.
Could you add to the ReadMe.
Thank you

**Comment by chcorbi** [comment]
Hi ckqsars,

The School Dataset is used in a few Multi-Task Learning (MTL) papers.
In "Convex Multi-Task Feature Learning", Argyriou et al. describe it in part 6.3.
http://ttic.uchicago.edu/~argyriou/papers/mtl_feat.pdf

Best,
